# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/saveRoute?route=Route1.xml
Accept: application/xml
Content-Type: application/xml
Cache-Control: no-cache

<?xml version="1.0"?>
<routes>
    <route name="Route 2">
        <routeleg>
            <pos>1</pos>
            <lnglat>(-26.577, 152.911)</lnglat>         <
        /routeleg>
    </route>
</routes>
###